build.xml, controller.xql, expath-pkg.xml, modules/lib/facets.xql, repo-config.xml, repo.xml, resources/xsl/tei2html.xsl
Merge upstream changes from the Srophe application into current app.
=> Srophe updates

manuscripts/facet-def.xml, manuscripts/search.html
Correct type in facets, fix search display.
=> Updates to facets. #10

modules/content-negotiation/content-negotiation.xql
https://github.com/majlis-erc/manuForma/issues/130
=> Updates bibliographic citation information for manuForm app

expath-pkg.xml, resources/xsl/majlis.xsl
=> Update xslt to fix #24

resources/xsl/core.xsl, resources/xsl/helper-functions.xsl, resources/xsl/majlis.xsl
Update available for MSS display.
=> Update manuscript layout. #42

modules/content-negotiation/content-negotiation.xql
https://github.com/majlis-erc/manuForma/issues/401
=> Update search for manuForma to include facets

resources/xsl/majlis.xsl
Add all titles to summary; #67
=> Update titles. #67

modules/content-negotiation/content-negotiation.xql
https://github.com/majlis-erc/manuForma/issues/425
=> Updates for biblIDs in xforms.

modules/content-negotiation/content-negotiation.xql
See: https://github.com/majlis-erc/manuForma/issues/484
=> Update search results.

resources/xsl/majlis.xsl
=> Update persons menu #99

modules/content-negotiation/content-negotiation.xql
Adds additional options for lookups, including searching in multiple collections. 
https://github.com/majlis-erc/manuForma/issues/584
=> Update search api for lookups.

resources/xsl/majlis.xsl
=> Revert "Update white space handling. #131"

modules/content-negotiation/content-negotiation.xql
https://github.com/majlis-erc/manuForma/issues/611
=> Update author lookup function for Works.

modules/app.xql, resources/xsl/majlis.xsl
=> Updates to display related mss in works records. #202

modules/lib/maps.xqm, places/browse.html, places/index.html, resources/xsl/majlis.xsl
Should fix all issues except the color change for the markers, which is slightly more complicated. Leaving as is for now.
=> Issue bug fix212

modules/content-negotiation/content-negotiation.xql
Creates new lookup with out idno for citation.
=> Updates for https://github.com/majlis-erc/manuForma/issues/722

modules/content-negotiation/tei2html.xqm
to show author name for each work in browse works page
=> new function tei2html:summary-view-work

modules/content-negotiation/tei2html.xqm
body/bibl/title[type=majlis-headword, lang=en][1], else title[type=majlis-headword][1] for works in browse works page
=> use text/title[majlis-headword] for titles in Browse Works page

resources/xsl/majlis.xsl
by adding a new template for that
=> handling whitespaces Bfore/after ( in funder text in html 

resources/xsl/majlis.xsl
first reflects on empty ( fol. ) strings in title in ms page
=> locus template changed to choose fol(s). if to|from vals != empty; 

resources/xsl/majlis.xsl
Other types get t:teiHeader/t:fileDesc/t:titleStmt/t:title[@level='a']
=> changed title of Works to text/body/bibl/title[@type='majlis-headword']

resources/css/app.css, resources/xsl/majlis.xsl
Language buttons for Works and using colors to cluster Titles that belong to the same Work.
=> Person works lang btn + clustering

resources/xsl/majlis.xsl
=> lang btn added to Person's Attested Names
